### ISSUE TITLE
positioning weirdness?

### ISSUE THREAD

**Issue by jbenet** [asciinema/asciinema#124]
See the positioning weirdness in this asciinema: https://asciinema.org/a/5mu1809wf8socszrxzk9bfvlv -- the terminal shows it correctly. (It's made with https://github.com/jpillora/ssh-tron)

**Comment by sickill** [comment]
Haha, this looks very funny :) The thing here is that web browsers don't always use the same width for monospace characters, contrary to what you may expect. For example, empty screen cell (represented by space character) can be 8 pixels wide, but the "⣤" character may be 7 pixels wide. That's why when something is drawn on the left all the characters on the right move right/left.

The player presents all terminal lines as span elements, grouping text with the same color attributes in the same span element. The only way to overcome the mentioned problem would be to use a table or render each single character in its own, fixed width span. That would make thousands of DOM elements, which could make it slower, and possibly it would not play well with copy-paste.

Also, see here: https://stackoverflow.com/questions/9351689/how-to-display-special-unicode-characters-using-monospace-font-in-html-with-pres

I welcome any suggestions for solving it.
