### ISSUE TITLE
delete from the command line

### ISSUE THREAD

**Issue by ivanov** [asciinema/asciinema#13]
I somehow was able to upload a screencast without logging in (just by logging in), and now there doesn't seem to be a way to delete this screencast. http://ascii.io/a/1062

I have tried logging in as user ~pi, but that did not help, it seems to think its some other user pi (pi is my local username on my machine)

**Comment by hparadiz** [comment]
I don't want to upload every clip of me screwing around just trying to get the bash prompt right because your default total ignores PS1 on my machine. 
`bash-3.2$`
instead of
`user@machine:~$`

How this is user friendly I will never know. But I do know that it's annoying the crap out of me that there's all these random files in my temp files that I will never end up uploading cause I don't want to.

And to locally delete I have to literally search for the file through my terminal. If I lose it I'm shit out of luck cause it's in some randomly named folder with hundred of other things.

Why can't you guys just use something easy and simple like `/tmp/asciinema-[randomcode].cast` ???

The website is a security nightmare and you instantly upload upon someone hitting enter with no ability to break. So if I accidentally opened my ssh key and happened to not kill -9 asciinema I guess whoooops there go all my SSH keys to your server.

My mind is blown that this 6 year old issue hasn't been addressed. Why the fuck do I have to `auth` to delete a local file? Oh by the way that doesn't even fucking work. I authed 5 times and it did nothing.
