### ISSUE TITLE
Access to my old account.

### ISSUE THREAD

**Issue by trusktr** [asciinema/asciinema#131]
I don't remember which email I used, so asking for an email to log in can lead to someone guessing and creating a bunch of accounts (like I just did).

If I could log in by username I'd be in already. I signed up back when asciinema was asciiio, and my username is `trusktr`.

Is there some way we can get me logged in?

**Comment by trusktr** [comment]
The site says

```
If you have already recorded an asciicast but you don't see it here then associate it with your account by running asciinema auth in your terminal.
```

then when I run `asciinema auth` it says

```
Open the following URL in a browser to register your API token and assign any recorded asc
iicasts to your profile:
https://asciinema.org/connect/650f54fe-18f0-442e-9e2d-7b2c2187d79f
```

and then when I open that link it takes right back to

```
If you have already recorded an asciicast but you don't see it here then associate it with your account by running asciinema auth in your terminal.
```

making an infinite loop.

**Comment by sickill** [comment]
@trusktr just tell me which email you want to use for your asciinema.org account (or send it to support@asciinema.org if you don't want to expose it here) and I'll assign it to your old account (back in ascii.io days there was no requirement to set your email on your account so that's why your attempts didn't result in matching with the existing account).

**Comment by trusktr** [comment]
Hi @sickill. joe@trusktr.io would be fine. Thanks!

**Comment by sickill** [comment]
There you go: https://asciinema.org/~trusktr

**Comment by trusktr** [comment]
@sickill Sweeeeeet. Thanks!
