### ISSUE TITLE
terminal playback controls

### ISSUE THREAD

**Issue by omaraboumrad** [asciinema/asciinema#133]
Hello,

It would be nice if `asciinema play <file>` supported some playback controls through intercepting keyboard commands, example but not limited to:

`Ctrl+P` Toggle pause/play at current play step.
`Ctrl+H` Move one step backwards
`Ctrl+L` Move one step forward

Given the local player blends in perfectly in the terminal, there's no need to show any information about these controls during the playback.

**Use Case**

If I'm running a presentation or a demo, I'd like to be able to control the playback instead of anticipating it during the recording time.

Thank you!

**Comment by omaraboumrad** [comment]
Related: #97

**Comment by renatomefidf** [comment]
I would also like to see this feature! :)

**Comment by cypa** [comment]
this feature is much needed for security audit purposes also

**Comment by robertpeteuil** [comment]
It's been a year, so I thought I'd surface this request again.

While I'm interested in the original request, I'm especially interested in the "play/pause" feature.  This would allow me to use asciinema in live presentations (where pausing is necessary for discussion or answering questions).  

Feature Request Enhancements:

- For the "live demo" scenario - mapping the "play/pause" action to a mouse button would be ideal
  - Most users are accustomed to using mouse-clicks to play/pause videos
  - Many presenters use use wireless mice for live presentations

- Instead of "Move one step backward", I'd prefer "jump 5 back seconds"
  - Essentially like "instant replay" on a DVR
  - This is useful for anyone wanting to re-watch an event that just occurred in a recording

**Comment by kostaz** [comment]
Actually, the lack of play controls in terminal (pause, play, fast-forward, fast-backward)
in the only feature that prevents this app from becoming mainstream.
:+1:

**Comment by sickill** [comment]
Pause, play and fast-forward would be easy to add.

Rewinding on the other hand is impossible with the current (simple) implementation of `asciinema play`. This page nicely describes this problem and how IPBT solves it: https://www.chiark.greenend.org.uk/~sgtatham/ipbt/ (when reading replace `ttyrec` with `asciinema` and you'll get the picture).

**Comment by robertpeteuil** [comment]
Thanks for sharing this info.  It makes the challenges of rewind very clear.

Simply adding play/pause would be a huge leap forward in usefulness.

**Comment by sickill** [comment]
Toggling pause with space + stepping a frame at a time with period just landed in develop branch and will be released in 2.0 🙂

**Comment by robertpeteuil** [comment]
Awesome. Thanks all!

**Comment by omaraboumrad** [comment]
Brilliant!
