### ISSUE TITLE
asciinema 1.3 does not provide a wrapper

### ISSUE THREAD

**Issue by carnager** [asciinema/asciinema#174]
Since asciinema is now installed in python's site-packages directory, the binary won't be in $PATH anymore. 

asciinema should probably provide a little wrapper to be placed in $PATH. I guess setup.py is the place to do this.

**Comment by sickill** [comment]
setup.py has it configured: https://github.com/asciinema/asciinema/blob/master/setup.py#L29
In all systems I checked asciinema installation it was correctly creating a wrapper script.

**Comment by fornwall** [comment]
When I installed from source with `python3.5 setup.py install`, the resulting installation did not have the asciinema command-line wrapper.

I noticed the warnings

    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'

I had to `pip3 install setuptools` - after that the installation correctly set up the bin/asciinema wrapper.

I don't know enough about python packaging to know if this is the expected behaviour or not.

**Comment by sickill** [comment]
Does anyone know a way to make it generate a wrapper in a reliable way (also in the absence of setuptools)?

**Comment by sickill** [comment]
This has been solved in #179, the fix will be part of the next release.

**Comment by sickill** [comment]
1.4.0 has been just released, including fix (#179) by @jakubjedelsky.
