### ISSUE TITLE
Play ascineema recording for given time-frame.

### ISSUE THREAD

**Issue by dipak-pawar** [asciinema/asciinema#201]
While editing an ASCiinema file, it would be nice to be able to stop a playback at given time.

Example:
 asciinema play  --start-at 12s --ends-at 34s  my.rec 
 asciinema play  --start-at 101l  --ends-at 412l my.rec

So the playback will start at 12s and end with 34s.

**Comment by dipak-pawar** [comment]
We have start-at implementaion in this #180. 

I will provide implementation for ends-at if it's not done already

**Comment by sickill** [comment]
I don't think this would be useful for many people, so probably not worth maintaining. Thanks for the idea anyway!

**Comment by dipak-pawar** [comment]
@sickill Do we have any way to convert recording into different frames using timeline with the help of json file?

**Comment by sickill** [comment]
I'm not sure I understand that... You mean like creating shorter recording based on the original one?

**Comment by dipak-pawar** [comment]
yes I want to create short version of recording with time frame based on original one.

**Comment by dipak-pawar** [comment]
@sickill Can you help in this?

**Comment by sickill** [comment]
It's not as simple as it seems :) Terminals are state machines, and the recording reflects a stream of text and commands to modify that state. Because of that you can't just skip first N bytes because the following commands may be depending on the state built up so far (by the first N bytes).

To achieve what you want we would need to have a tool which would interpret the stream up to a point where you want the recording to start, and dump that state as a stream of bytes, basically establishing the "initial frame". We don't have such a tool right now unfortunatelly.

**Comment by dipak-pawar** [comment]
Thanks @sickill
