### ISSUE TITLE
Custom theme in .cast file is not used.

### ISSUE THREAD

**Issue by zefei** [asciinema/asciinema#305]
Hi, thank you for the wonderful tool that asciinema is!

I wanted to use some custom terminal color theme, and followed the v2 doc, manually added a "theme" attribute in my .cast file. But once the file is uploaded to asciinema.org, the player doesn't seem to use the color values. The file is uploaded to https://asciinema.org/a/y3oFQ2Tf5o61oLwPX4iEqI8CD and it should use a black on white theme.

Thank you!

**Comment by sickill** [comment]
That's correct. asciicast v2 spec reserved a place for custom theme, but the web player doesn't support it yet.

When I finish work on [SVG thumbnails](https://github.com/asciinema/asciinema-server/pull/304) I'll take a look at this (custom color themes should be honored by both the player and SVG).

**Comment by zefei** [comment]
Thank you for the explanation and this wonderful tool!

**Comment by iology** [comment]
voting for this feature @sickill

**Comment by uncenter** [comment]
Can this be reopened since it isn't actually solved/completed?

**Comment by ku1ik** [comment]
Looks good to me:

<img width="1262" height="712" alt="Image" src="https://github.com/user-attachments/assets/5b942df8-44b0-4db0-b773-fa4a2e196bbb" />

Does it look different for you?

**Comment by bonswouar** [comment]
After digging a bit it seems there are only two tiny issues:
- The colors were originally a bit wrong for me, but I've found out it was because of Darkreader extension. A global dark theme toggle for the website could fix that maybe (so that it's detected as dark theme by the extension and isn't ) 
- The background shouldn't be black, I've just checked the cast file and there is `"bg": "#24273a"`, not sure why it isn't applied?
