### ISSUE TITLE
Delete local from Command Line!

### ISSUE THREAD

**Issue by hparadiz** [asciinema/asciinema#306]
I don't want to upload every clip of me screwing around just trying to get the bash prompt right because your default total ignores PS1 on my machine. 
`bash-3.2$`
instead of
`user@machine:~$`

How this is user friendly I will never know. But I do know that it's annoying the crap out of me that there's all these random files in my temp files that I will never end up uploading cause I don't want to.

And to locally delete I have to literally search for the file through my terminal. If I lose it I'm shit out of luck cause it's in some randomly named folder with hundred of other things.

Why can't you guys just use something easy and simple like `/tmp/asciinema-[randomcode].cast` ???

### The website is a security nightmare and you instantly upload upon someone hitting enter with no ability to break. If I accidentally opened my ssh keys and don't immediately kill -9 asciinema I guess whoooops there go all my SSH keys to your server.

#13 
My mind is blown that this 6 year old issue hasn't been addressed. Why do I have to `auth` to delete a local file? Oh by the way that doesn't even work. I authed 5 times and it did nothing.

**Comment by sickill** [comment]
Maybe asciinema is not the right tool for you, sorry!

**Comment by jikkuatwork** [comment]
I am sorry! But this flow is so draconian! I can't believe how such a system is designed creating an auth system right when its installed and the default option just uploads!!

I am stunned why no one else is freaking out! This is a great utility with a pathetic flow! 

I just uploaded something without realizing it was being uploaded and when I tried to delete it, its asking for my email!! What nonsense is this?

The default `asciinema rec` sending directly to server is so bad, I am sorry for ranting against an otherwise great OS project. But this is clearly very bad design, especially for your end users. 

Please consider changing this.

**Comment by sickill** [comment]
@jikkuatwork  Well, you get prompt asking you to confirm upload:

"press <enter> to upload to asciinema.org, <ctrl-c> to save locally"

You can decide to either upload or save it locally (file in /tmp gets preserved). If you don't read the prompt and blindly confirm with enter then it's your problem.

Having said that, I'm considering changing the behaviour in the next major version of the recorder. This topic has also been discussed here: https://github.com/orgs/asciinema/discussions/31
