### ISSUE TITLE
a way to claim already uploaded recordings?

### ISSUE THREAD

**Issue by andy108369** [asciinema/asciinema#519]
Say I have uploaded some recordings to the asciinema but forgot to `asciinema auth`, is there a way to authenticate / claim them?

**Comment by andy108369** [comment]
I guess I'd need to [download them](https://github.com/asciinema/asciinema/issues/99#issuecomment-101673895) until they haven't been archived yet and then push them back (`asciinema upload file.json`) once I `asciinema auth`'ed again.

Before I close this one, is there a way to download the archived recordings?

Such as these 3:

https://asciinema.org/a/uQZd1CmJZrT07xtoUadJBC6Ty

https://asciinema.org/a/62remtasmt80i4pk63cfu36fp

https://asciinema.org/a/2yy003e6xd0s4qrfcfkurzmge

**Comment by tcarreira** [comment]
From what I'm able to see, when no `asciinema auth` is run, there is a different link for claiming that record:
Look:
[![asciicast](https://asciinema.org/a/525945.svg)](https://asciinema.org/a/525945)

**Comment by tcarreira** [comment]
> I'm getting 404 on your link:

oops, the link was private. It's public now. @andy108369

**Comment by andy108369** [comment]
> > I'm getting 404 on your link:
> 
> oops, the link was private. It's public now. @andy108369

Cool, it works now. 

How do I derive the number off of the above 3 links that I've got archived?

**Comment by tcarreira** [comment]
> How do I derive the number off of the above 3 links that I've got archived?

From what I'm seeing, you cannot.

Upon a recording, you get that uuid for reclaiming the recording.
If you do not claim that, the recording will be deleted after 7 days. 
If you have a recording link, and it is currently working, I shall assume it was claimed by someone (or else, it is some old behavior I don't know about)

**Comment by sickill** [comment]
Archived is slightly different than deleted - it's hidden/inaccesible, but recoverable upon request. Periodically (irregularly) I do delete recordings which were in archived state for a long time.

**Comment by sickill** [comment]
If you upload first, forgetting to `asciinema auth`, you can still `asciinema auth` later from the same machine and it will link the recordings to your asciinema.org account. In other words: you can do it in any order, as long as you do it from the same machine (and system user).

You can't claim a recording from another system because the thing that links you to your recordings is "installation ID" stored in ~/.config/asciinema dir. Unless you sync your asciinema installation ID file across machines, but that's not recommended (although would work).

**Comment by sickill** [comment]
@andy108369 I've recovered your 3 old recordings.
