### ISSUE TITLE
Replaying recording shows (newlines at every new character in kitty/alacritty) with a specific shell setup

### ISSUE THREAD

**Issue by AkechiShiro** [asciinema/asciinema#566]
**Describe the bug**
Replay looks like this : 
![image](https://github.com/asciinema/asciinema/assets/14914796/d5461930-5233-4e17-ba91-7a7596714744)

**To Reproduce**
0. Open Kitty terminal
1. asciinema rec -i 2 rec.rec
2. Write commands
3. If bash is used as a shell (in Kitty via the terminal, then the issue is gone/fixed temporarily)

**Expected behavior**
Replay should be replayed correctly in Kitty using Zsh and Powerlevel11k shell theme with a NerdFont patched.

**Versions:**
 - OS: ArchLinux
 - asciinema cli: asciinema 2.3.0

**Additional context**Add any other context about the problem here.

See 3.

**Comment by AkechiShiro** [comment]
Do you need the capture or will you be able to reproduce the issue ?

**Comment by AkechiShiro** [comment]
I believe #368 is the fix, why is it not yet merged in ?

**Comment by AkechiShiro** [comment]
@ku1ik

**Comment by AkechiShiro** [comment]
I haven't tested the fix yet, but will soon.

**Comment by ku1ik** [comment]
#368 is not a fix that resolves the issue here, it just adds a warning. You would still get broken output if we merged it.

There's no easy fix for this, as you can't really fit longer lines (recorded) into shorter lines (current terminal width during playback).

The best we can do is to add the warning so user can expect corrupted output, but we can potentially detect if the corruption would happen (see https://github.com/asciinema/asciinema/pull/368#issuecomment-1790572425 for the idea).
